### ISSUE TITLE
Brush Radius

### ISSUE THREAD

**Issue by akilmonster143** [baaivision/Painter#65]
Traceback (most recent call last):
  File "c:\Users\Akil\Downloads\Painter-main\Painter-main\SegGPT\app_gradio.py", line 127, in <module>
    inputs=[gr.ImageMask(brush_radius=8, label="prompt (提示图)"), gr.Image(label="img1 (测试图1)"), gr.Image(label="img2 (测试图2)")],
  File "C:\Users\Akil\Downloads\Painter-main\Painter-main\my_env\lib\site-packages\gradio\component_meta.py", line 157, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'brush_radius'

**Comment by traverso-inspectifai** [comment]
I am having the same issue

**Comment by Richard1Bob** [comment]
I have tried to install gradio to the specified version the way you did, but the result is the same:
Traceback (most recent call last):
  File "E:\ScribblePrompt\ScribblePrompt-0.1.0\demos\app.py", line 450, in <module>
    scribble_img = gr.Image(
  File "D:\ProgramData\Anaconda3\lib\site-packages\gradio\component_meta.py", line 167, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'brush_radius'

> Hi, @akileswarpaidi and @traverso-inspectifai . I was able to resolve this issue by installing the Gradio `3.22.1` version.
