### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (152960,) (458880,) 

### ISSUE THREAD

**Issue by OkGuai** [baaivision/Painter#77]
I'm getting the following error when I try to infer from an image. 
+ NUM_GPUS=1
+ JOB_NAME=painter_vit_large
+ CKPT_FILE=painter_vit_large.pth
+ PROMPT=ADE_train_00001098
+ SIZE=448
+ MODEL=painter_vit_large_patch16_input896x448_win_dec64_8glb_sl1
+ CKPT_PATH=premodel/painter_vit_large.pth
+ DST_DIR=models_inference/premodel/ade20k_semseg_inference_painter_vit_large.pth_ADE_train_00001098_size448
+ python eval/ade20k_semantic/ADE20kSemSegEvaluatorCustom.py --pred_dir models_inference/premodel/ade20k_semseg_inference_painter_vit_large.pth_ADE_train_00001098_size448
10
10
loading predictions
processing
  0%|                                                    | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/workspace/Painter/Painter/eval/ade20k_semantic/ADE20kSemSegEvaluatorCustom.py", line 178, in <module>
    evaluator.process(inputs, outputs)
  File "/mnt/workspace/Painter/Painter/eval/ade20k_semantic/ADE20kSemSegEvaluatorCustom.py", line 101, in process
    (self._num_classes + 1) * pred.reshape(-1) + gt.reshape(-1),
ValueError: operands could not be broadcast together with shapes (152960,) (458880,)

**Comment by OkGuai** [comment]
Any help would be very much appreciated.
